// supabase/functions/send-report-email/index.ts
//
// Sends the MINERVIUM report notification email automatically —
// no Gmail/Outlook window, no user interaction required. Called from
// the app right after a report is saved.
//
// SETUP REQUIRED before this works (same as the action-reminders
// function — if you already set that one up, you're done, this reuses
// the same secrets):
// 1. Sign up at resend.com (free tier), get an API key.
// 2. Supabase dashboard -> Edge Functions -> Secrets, add:
//      RESEND_API_KEY = <your key>
//      REMINDER_FROM_EMAIL = alerts@yourdomain.com
//      (or Resend's onboarding@resend.dev sandbox address while testing)
// 3. Deploy:  supabase functions deploy send-report-email
//
// I can't test this end-to-end from here — it needs to run inside
// your real Supabase project with a real Resend account.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

// CORS: the browser sends a preflight OPTIONS request before the real POST
// (supabase.functions.invoke always triggers one, since it sets custom
// headers). Without these headers that preflight fails and the browser
// never even attempts the real request — it shows up in the logs as
// "OPTIONS | 500" and the app reports "Couldn't send automatically".
const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { to, report, profile, pdfBase64, pdfFilename } = await req.json();

    if (!to || to.length === 0) {
      return new Response(JSON.stringify({ error: "No recipients provided" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const dateTime = new Date(report.created_at || Date.now()).toLocaleString("en-CA", {
      dateStyle: "medium",
      timeStyle: "short",
    });

    const body = `Hello,

A new safety report has been submitted through the MINERVIUM Safety Application.

Report details

* Report Type: ${report.report_type || "—"}
* Project: ${report.project || "—"}
* Area/Location: ${report.location || "—"}
* Submitted By: ${profile?.my_name || report.respondent || "—"}
* Company: ${report.company || "—"}
* Date and Time: ${dateTime}
* Risk Rating: ${report.risk_rating || "—"}
* Status: ${report.status || "Open"}

Please find the complete safety report attached, including the observation details, photographs, contributing factors, and any recommended corrective or preventive actions.
Please review the attached report and take the required action, where applicable.
For reports requiring follow-up, please provide an update regarding the assigned responsible person, proposed action, and expected completion date.

This is an automated notification generated by the MINERVIUM Safety Application.

Observe • Share • Prevent • Improve
MINERVIUM Safety
${report.project || ""}
`;

    // Branded HTML version (logo header + signature). The plain-text `body`
    // above is still sent alongside it for clients that don't render HTML.
    const esc = (v: unknown) =>
      String(v ?? "—").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
    const SITE = "https://omsf-site-app.vercel.app/branding";
    const rows: [string, string][] = [
      ["Report Type", report.report_type || "—"],
      ["Project", report.project || "—"],
      ["Area/Location", report.location || "—"],
      ["Submitted By", profile?.my_name || report.respondent || "—"],
      ["Company", report.company || "—"],
      ["Date and Time", dateTime],
      ["Risk Rating", report.risk_rating || "—"],
      ["Status", report.status || "Open"],
    ];
    const detailRows = rows.map(([k, v]) =>
      `<tr><td style="padding:7px 12px 7px 0;color:#5C6870;font-size:14px;white-space:nowrap;vertical-align:top;">${esc(k)}</td><td style="padding:7px 0;color:#0d1b26;font-size:14px;font-weight:600;">${esc(v)}</td></tr>`
    ).join("");
    const html = `<!doctype html><html><body style="margin:0;padding:0;background:#EEF2F4;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#EEF2F4;padding:24px 12px;"><tr><td align="center">
<table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#ffffff;border-radius:14px;overflow:hidden;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;">
  <tr><td align="center" style="background:#08131D;padding:22px 16px 16px;">
    <img src="${SITE}/email/lockup.png" width="170" alt="MINERVIUM" style="display:block;border:0;height:auto;max-width:170px;">
  </td></tr>
  <tr><td style="height:3px;background:#18C9CB;line-height:3px;font-size:3px;">&nbsp;</td></tr>
  <tr><td style="padding:26px 28px 6px;color:#0d1b26;font-size:15px;line-height:1.6;">
    <p style="margin:0 0 12px;">Hello,</p>
    <p style="margin:0 0 18px;">A new safety report has been submitted through the <b>MINERVIUM Safety Application</b>.</p>
    <p style="margin:0 0 6px;font-size:12px;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;color:#18A7A9;">Report details</p>
    <table role="presentation" cellpadding="0" cellspacing="0" style="border-top:1px solid #E3E8EB;width:100%;">${detailRows}</table>
    <p style="margin:20px 0 10px;">Please find the complete safety report attached, including the observation details, photographs, contributing factors, and any recommended corrective or preventive actions.</p>
    <p style="margin:0 0 10px;">Please review the attached report and take the required action, where applicable.</p>
    <p style="margin:0 0 18px;">For reports requiring follow-up, please provide an update regarding the assigned responsible person, proposed action, and expected completion date.</p>
    <p style="margin:0 0 4px;color:#73828B;font-size:12.5px;">This is an automated notification generated by the MINERVIUM Safety Application.</p>
  </td></tr>
  <tr><td style="padding:10px 28px 26px;">
    <table role="presentation" cellpadding="0" cellspacing="0" style="border-top:1px solid #E3E8EB;width:100%;"><tr>
      <td style="padding-top:16px;width:64px;vertical-align:middle;"><img src="${SITE}/email/emblem.png" width="52" alt="MINERVIUM" style="display:block;border:0;height:auto;"></td>
      <td style="padding-top:16px;vertical-align:middle;font-size:13px;line-height:1.5;color:#0d1b26;">
        <b style="font-size:14px;">MINERVIUM Safety</b><br>
        ${esc(report.project || "")}<br>
        <span style="color:#18A7A9;font-weight:600;">Observe &bull; Share &bull; Prevent &bull; Improve</span>
      </td>
    </tr></table>
  </td></tr>
</table>
</td></tr></table></body></html>`;

    const subject = `[MINERVIUM] ${report.report_type || "Safety"} Report — ${report.location || "OMSF"}`;

    // The PDF is built client-side (same layout as the "PDF" button on the
    // report detail screen) and handed to us already-encoded — this function
    // never generates the PDF itself, it just attaches what it was given.
    const attachments = pdfBase64
      ? [{ filename: pdfFilename || `Report_${report.report_date || "report"}.pdf`, content: pdfBase64 }]
      : [];

    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${Deno.env.get("RESEND_API_KEY")}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: Deno.env.get("REMINDER_FROM_EMAIL"),
        to,
        subject,
        text: body,
        html,
        ...(attachments.length ? { attachments } : {}),
      }),
    });

    if (!res.ok) {
      const errText = await res.text();
      console.error("Resend error:", errText);
      return new Response(JSON.stringify({ error: errText }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    return new Response(JSON.stringify({ sent: true }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err) {
    console.error(err);
    return new Response(JSON.stringify({ error: String(err) }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
