// supabase/functions/send-report-email/index.ts
//
// Sends the MINERVIUM report notification email automatically —
// no Gmail/Outlook window, no user interaction required. Called from
// the app right after a report is saved.
//
// SETUP REQUIRED before this works (same as the action-reminders
// function — if you already set that one up, you're done, this reuses
// the same secrets):
// 1. Sign up at resend.com (free tier), get an API key.
// 2. Supabase dashboard -> Edge Functions -> Secrets, add:
//      RESEND_API_KEY = <your key>
//      REMINDER_FROM_EMAIL = alerts@yourdomain.com
//      (or Resend's onboarding@resend.dev sandbox address while testing)
// 3. Deploy:  supabase functions deploy send-report-email
//
// I can't test this end-to-end from here — it needs to run inside
// your real Supabase project with a real Resend account.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

// CORS: the browser sends a preflight OPTIONS request before the real POST
// (supabase.functions.invoke always triggers one, since it sets custom
// headers). Without these headers that preflight fails and the browser
// never even attempts the real request — it shows up in the logs as
// "OPTIONS | 500" and the app reports "Couldn't send automatically".
const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { to, report, profile, pdfBase64, pdfFilename } = await req.json();

    if (!to || to.length === 0) {
      return new Response(JSON.stringify({ error: "No recipients provided" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const dateTime = new Date(report.created_at || Date.now()).toLocaleString("en-CA", {
      dateStyle: "medium",
      timeStyle: "short",
    });

    const body = `Hello,

A new safety report has been submitted through the MINERVIUM Safety Application.

Report details

* Report Type: ${report.report_type || "—"}
* Project: ${report.project || "—"}
* Area/Location: ${report.location || "—"}
* Submitted By: ${profile?.my_name || report.respondent || "—"}
* Company: ${report.company || "—"}
* Date and Time: ${dateTime}
* Risk Rating: ${report.risk_rating || "—"}
* Status: ${report.status || "Open"}

Please find the complete safety report attached, including the observation details, photographs, contributing factors, and any recommended corrective or preventive actions.
Please review the attached report and take the required action, where applicable.
For reports requiring follow-up, please provide an update regarding the assigned responsible person, proposed action, and expected completion date.

This is an automated notification generated by the MINERVIUM Safety Application.

Observe • Share • Prevent • Improve
MINERVIUM Safety
${report.project || ""}
`;

    const subject = `[MINERVIUM] ${report.report_type || "Safety"} Report — ${report.location || "OMSF"}`;

    // The PDF is built client-side (same layout as the "PDF" button on the
    // report detail screen) and handed to us already-encoded — this function
    // never generates the PDF itself, it just attaches what it was given.
    const attachments = pdfBase64
      ? [{ filename: pdfFilename || `Report_${report.report_date || "report"}.pdf`, content: pdfBase64 }]
      : [];

    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${Deno.env.get("RESEND_API_KEY")}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: Deno.env.get("REMINDER_FROM_EMAIL"),
        to,
        subject,
        text: body,
        ...(attachments.length ? { attachments } : {}),
      }),
    });

    if (!res.ok) {
      const errText = await res.text();
      console.error("Resend error:", errText);
      return new Response(JSON.stringify({ error: errText }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    return new Response(JSON.stringify({ sent: true }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err) {
    console.error(err);
    return new Response(JSON.stringify({ error: String(err) }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
